# NOTE: exclude
#  Single file/folder -> exclude: examples/.*ipynb
#  Multiple file/folder -> exclude: (^.*<folder_name>/|examples/.*ipynb)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      #  - id: check-symlinks
      #  - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      # - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: fix-encoding-pragma
        args: ["--remove"]
        description: Removes the encoding-pragma since python3 codes are utf-8 by default
      - id: check-added-large-files
        args: ["--maxkb=15000"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.26
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/ansible/ansible-lint
    rev: v26.1.1
    hooks:
      - id: ansible-lint
