[project]
name = "ansible-automations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.11"
dependencies = [
    "ansible-dev-tools>=26.1.0",
    "passlib>=1.7.4",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
