env_vars_mapping:
  ARCANE_CLIENT_ID:
    item: "ilker.pocketid"
    field: "ARCANE_CLIENT_ID"
  ARCANE_CLIENT_SECRET:
    item: "ilker.pocketid"
    field: "ARCANE_CLIENT_SECRET"
  ARCANE_ENCRYPTION_KEY:
    item: "arcane.gpu"
    field: "ARCANE_ENCRYPTION_KEY"
  ARCANE_JWT_SECRET:
    item: "arcane.gpu"
    field: "ARCANE_JWT_SECRET"
  BESZEL_EMAIL:
    item: "beszel.gpu"
    field: "username"
  BESZEL_PASSWORD:
    item: "beszel.gpu"
    field: "password"
  BICHON_ENCRYPT_PASSWORD:
    item: "mailarchive.gpu.me"
    field: "BICHON_ENCRYPT_PASSWORD"
  CHANGEDETECTION_API_KEY:
    item: "changedetection.gpu"
    field: "CHANGEDETECTION_API_KEY"
  CUSTOM_OPENAI_API_KEY:
    item: "chat.gpu"
    field: "CUSTOM_OPENAI_API_KEY"
  CUSTOM_OPENAI_BASE_URL:
    item: "chat.gpu"
    field: "CUSTOM_OPENAI_BASE_URL"
  CUSTOM_OPENAI_MODEL_NAME:
    item: "chat.gpu"
    field: "CUSTOM_OPENAI_MODEL_NAME"
  DOMAINNAME:
    item: "Homeserver.gpu"
    field: "DOMAINNAME"
  GOTIFY_LOGGIFLY_APPRISE_URL:
    item: "gotify.remoteserver"
    field: "GOTIFY_LOGGIFLY_APPRISE_URL"
  IMMICH_API_KEY:
    item: " immich.photos.me"
    field: "IMMICH_API_KEY"
  IMMICH_DB_DATABASE_NAME:
    item: "Homeserver.gpu"
    field: "IMMICH_DB_DATABASE_NAME"
  IMMICH_DB_HOSTNAME:
    item: "Homeserver.gpu"
    field: "IMMICH_DB_HOSTNAME"
  IMMICH_DB_PASSWORD:
    item: "Homeserver.gpu"
    field: "IMMICH_DB_PASSWORD"
  IMMICH_DB_USERNAME:
    item: "Homeserver.gpu"
    field: "IMMICH_DB_USERNAME"
  IMMICH_REDIS_HOSTNAME:
    item: "Homeserver.gpu"
    field: "IMMICH_REDIS_HOSTNAME"
  IMMICH_UPLOAD_LOCATION:
    item: "Homeserver.gpu"
    field: "IMMICH_UPLOAD_LOCATION"
  JELLYSEERR_API_KEY:
    item: "jellyseerr.gpu"
    field: "JELLYSEERR_API_KEY"
  KOMODO_DB_PASSWORD:
    item: "Homeserver.gpu"
    field: "KOMODO_DB_PASSWORD"
  KOMODO_DB_USERNAME:
    item: "Homeserver.gpu"
    field: "KOMODO_DB_USERNAME"
  LANGFUSE_CLICKHOUSE_PASSWORD:
    item: "Homeserver.gpu"
    field: "LANGFUSE_CLICKHOUSE_PASSWORD"
  LANGFUSE_CLICKHOUSE_USER:
    item: "Homeserver.gpu"
    field: "LANGFUSE_CLICKHOUSE_USER"
  LANGFUSE_ENCRYPTION_KEY:
    item: "Homeserver.gpu"
    field: "LANGFUSE_ENCRYPTION_KEY"
  LANGFUSE_INIT_USER_EMAIL:
    item: "langfuse.gpu"
    field: "username"
  LANGFUSE_INIT_USER_NAME:
    item: "Homeserver.gpu"
    field: "LANGFUSE_INIT_USER_NAME"
  LANGFUSE_INIT_USER_PASSWORD:
    item: "langfuse.gpu"
    field: "password"
  LANGFUSE_REDIS_PASSWORD:
    item: "Homeserver.gpu"
    field: "LANGFUSE_REDIS_PASSWORD"
  LANGFUSE_SALT_NEXTAUTH_SECRET:
    item: "Homeserver.gpu"
    field: "LANGFUSE_SALT_NEXTAUTH_SECRET"
  LANGFUSE_SALT:
    item: "Homeserver.gpu"
    field: "LANGFUSE_SALT"
