env_vars_mapping:
  DOMAINNAME:
    item: "Homeserver.remoteserver"
    field: "DOMAINNAME"
  GOTIFY_DEFAULT_USER_PASS:
    item: "gotify.remoteserver"
    field: "password"
  GOTIFY_GATUS_NOTIFICATION_TOKEN:
    item: "gotify.remoteserver"
    field: "GOTIFY_GATUS_NOTIFICATION_TOKEN"
  GOTIFY_HOMEPAGE_CLIENT_TOKEN:
    item: "gotify.remoteserver"
    field: "GOTIFY_HOMEPAGE_CLIENT_TOKEN"
  PGID:
    item: "Homeserver.remoteserver"
    field: "PGID"
  PUID:
    item: "Homeserver.remoteserver"
    field: "PUID"
  # TODO: Get from `{{ repo_path }}` ansible env
  REPO_PATH:
    item: "Homeserver.remoteserver"
    field: "REPO_PATH"
  RYBBIT_BETTER_AUTH_SECRET:
    item: "Homeserver.remoteserver"
    field: "RYBBIT_BETTER_AUTH_SECRET"
  # TODO: Get from `{{ username }}` ansible env
  USERDIR:
    item: "Homeserver.remoteserver"
    field: "USERDIR"
