env_vars_mapping:
  DOCKERDIR:
    item: "Homeserver.remoteserver"
    field: "DOCKERDIR"
  DOMAINNAME:
    item: "Homeserver.remoteserver"
    field: "DOMAINNAME"
  GOTIFY_DEFAULT_USER_PASS:
    item: "gotify.remoteserver"
    field: "password"
  GOTIFY_GATUS_NOTIFICATION_TOKEN:
    item: "gotify.remoteserver"
    field: "GOTIFY_GATUS_NOTIFICATION_TOKEN"
  GOTIFY_HOMEPAGE_CLIENT_TOKEN:
    item: "gotify.remoteserver"
    field: "GOTIFY_HOMEPAGE_CLIENT_TOKEN"
  PGID:
    item: "Homeserver.remoteserver"
    field: "PGID"
  PUID:
    item: "Homeserver.remoteserver"
    field: "PUID"
  USERDIR:
    item: "Homeserver.remoteserver"
    field: "USERDIR"
