env_vars_mapping:
  CHANGEDETECTION_API_KEY:
    item: "changedetection.gpu"
    field: "CHANGEDETECTION_API_KEY"
  DIR_HARDDISKROOT:
    item: "Homeserver.rpi0"
    field: "DIR_HARDDISKROOT"
  DIR_NOTES:
    item: "Homeserver.rpi0"
    field: "DIR_NOTES"
  DOMAINNAME:
    item: "Homeserver.rpi0"
    field: "DOMAINNAME"
  GITHUB_DASHBOARD_TOKEN:
    item: "github.sigirciilker"
    field: "GITHUB_DASHBOARD_TOKEN"
  GLANCE_SECRET_TOKEN:
    item: "Homeserver.rpi0"
    field: "GLANCE_SECRET_TOKEN"
  HASS_API_KEY:
    item: "homeassistant.home"
    field: "HASS_API_KEY"
  HEADSCALE_API_KEY:
    item: "headscale.remoteserver"
    field: "HEADSCALE_API_KEY"
  JELLYFIN_API_KEY:
    item: "jellyfin.gpu"
    field: "JELLYFIN_API_KEY"
  JELLYFIN_URL:
    item: "Homeserver.rpi0"
    field: "JELLYFIN_URL"
  JELLYFIN_USER_ID:
    item: "jellyfin.gpu"
    field: "JELLYFIN_USER_ID"
  MAXMIND_LICENSE_KEY:
    item: "maxmind.com"
    field: "MAXMIND_LICENSE_KEY"
  NETWORK_INTERFACE_NAMES:
    item: "Homeserver.rpi0"
    field: "NETWORK_INTERFACE_NAMES"
  POCKETID_ENCRYPTION_KEY:
    item: "Homeserver.rpi0"
    field: "POCKETID_ENCRYPTION_KEY"
  SYNCTHING_API_KEY:
    item: "syncthing.home"
    field: "SYNCTHING_API_KEY"
  SYNCTHING_NOTES_FOLDER_ID:
    item: "syncthing.home"
    field: "SYNCTHING_NOTES_FOLDER_ID"
  QUARTZ_REBUILD_WEBHOOK_SECRET:
    item: "Homeserver.rpi0"
    field: "QUARTZ_REBUILD_WEBHOOK_SECRET"
  TMDB_API_READ_ACCESS_TOKEN:
    item: "tmdb.themoviedb"
    field: "TMDB_API_READ_ACCESS_TOKEN"
  TRAKT_CLIENT_ID:
    item: "trakt.tv"
    field: "TRAKT_GLANCE_CLIENT_ID"
  TRAKT_USERNAME:
    item: "trakt.tv"
    field: "username"
  VAULTWARDEN_ADMIN_TOKEN:
    item: "Homeserver.rpi0"
    field: "VAULTWARDEN_ADMIN_TOKEN"
