env_vars_mapping:
  CHANGEDETECTION_API_KEY:
    item: "changedetection.gpu"
    field: "CHANGEDETECTION_API_KEY"
  DOMAINNAME:
    item: "Homeserver.rpi0"
    field: "DOMAINNAME"
  GITHUB_DASHBOARD_TOKEN:
    item: "github.sigirciilker"
    field: "GITHUB_DASHBOARD_TOKEN"
  HEADSCALE_API_KEY:
    item: "headscale.remoteserver"
    field: "HEADSCALE_API_KEY"
  JELLYFIN_API_KEY:
    item: "jellyfin.gpu"
    field: "JELLYFIN_API_KEY"
  JELLYFIN_URL:
    item: "Homeserver.rpi0"
    field: "JELLYFIN_URL"
  JELLYFIN_USER_ID:
    item: "jellyfin.gpu"
    field: "JELLYFIN_USER_ID"
  LOCAL_STATIC_IP:
    item: "Homeserver.rpi0"
    field: "LOCAL_STATIC_IP"
  POCKETID_ENCRYPTION_KEY:
    item: "Homeserver.rpi0"
    field: "POCKETID_ENCRYPTION_KEY"
  QUARTZ_REBUILD_WEBHOOK_SECRET:
    item: "Homeserver.rpi0"
    field: "QUARTZ_REBUILD_WEBHOOK_SECRET"
  TMDB_API_READ_ACCESS_TOKEN:
    item: "tmdb.themoviedb"
    field: "TMDB_API_READ_ACCESS_TOKEN"
  TRAKT_CLIENT_ID:
    item: "trakt.tv"
    field: "TRAKT_GLANCE_CLIENT_ID"
  TRAKT_USERNAME:
    item: "trakt.tv"
    field: "username"
  VAULTWARDEN_ADMIN_TOKEN:
    item: "Homeserver.rpi0"
    field: "VAULTWARDEN_ADMIN_TOKEN"
