env_vars_mapping:
  ADGUARD_PASSWORD:
    item: "adguard.rpi1"
    field: "password"
  ADGUARD_USERNAME:
    item: "adguard.rpi1"
    field: "username"
  DIR_HARDDISKROOT:
    item: "Homeserver.rpi1"
    field: "DIR_HARDDISKROOT"
  DOMAINNAME:
    item: "Homeserver.rpi1"
    field: "DOMAINNAME"
  LOCAL_STATIC_IP:
    item: "Homeserver.rpi1"
    field: "LOCAL_STATIC_IP"
