env_vars_mapping:
  ADGUARD_PASSWORD:
    item: "adguardhome.rpi1"
    field: "password"
  ADGUARD_USERNAME:
    item: "adguardhome.rpi1"
    field: "username"
  DIR_HARDDISKROOT:
    item: "Homeserver.rpi1"
    field: "DIR_HARDDISKROOT"
  DOMAINNAME:
    item: "Homeserver.rpi1"
    field: "DOMAINNAME"
  NETWORK_INTERFACE_NAMES:
    item: "Homeserver.rpi1"
    field: "NETWORK_INTERFACE_NAMES"
