env_vars_mapping:
  DIR_HARDDISKROOT:
    item: "Homeserver.rpi3"
    field: "DIR_HARDDISKROOT"
  DOMAINNAME:
    item: "Homeserver.rpi3"
    field: "DOMAINNAME"
  LOCAL_STATIC_IP:
    item: "Homeserver.rpi3"
    field: "LOCAL_STATIC_IP"
