---
user_name: ilker
user_password: ilker
ansible_user: "{{ user_name }}"
repo_url: git@github.com:ilkersigirci/homeserver-docker.git
repo_path: "/home/{{ user_name }}/docker"
ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFadqKW8w7ESy4RpHpHiADosfPCN3fDBKBXPxqhw7LGj homeserver-docker"
